version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "maintainer-team"
    assignees:
      - "security-team"
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
      - "rust"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainer-team"
    commit-message:
      prefix: "chore(ci):"
    labels:
      - "dependencies"
      - "github-actions"